### ISSUE TITLE
TypeError: Required argument 'vtln_warp' (pos 3) not found

### ISSUE THREAD

**Issue by xbsdsongnan** [tencent-ailab/pika#4]
bash train_transducer_bmuf_otfaug.sh

/utils/compute_global_cmvn.py", line 64, in <module>
    vtnl_warp=1.0)
TypeError: Required argument 'vtln_warp' (pos 3) not found

**Comment by cweng6** [comment]
This is due to typos in older version pykaldi, could you try to change 'vtnl_warp' to 'vtln_warp' in these two lines,
https://github.com/tencent-ailab/pika/blob/23c4cddef4392bc035207187d3b5653e9a3f083e/utils/compute_global_cmvn.py#L64

https://github.com/tencent-ailab/pika/blob/23c4cddef4392bc035207187d3b5653e9a3f083e/loader/otf_utt_loader.py#L234

**Comment by xbsdsongnan** [comment]
thank you very much

**Comment by xbsdsongnan** [comment]
thank you very much@cweng6
